name: build

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install third party dependencies
      run: sudo apt install build-essential libssl-dev zlib1g-dev libsqlite3-dev libz-dev curl gem ruby unzip p7zip-full unrar-free
    - name: Git Clone LDB
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: scanoss/ldb
        platform: github
        ref: master
        path: ldb
    - name: Build LDB
      run: cd ldb && make && sudo make install && sudo mkdir /var/lib/ldb
    - name: make
      run: make
    - name: version
      run: echo "::set-output name=version::$(./scanoss -version)"
      id: version
    - name: Test output
      run: |
       echo ${{ steps.version.outputs.version }}

    - uses: singingwolfboy/build-dpkg-buster@v1
      id: build
      with:
        args: --unsigned-source --unsigned-changes

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: dist
        path: |
          ${{ steps.build.outputs.scanoss }}
          LICENSE
        retention-days: 5

