name: deploy

on: 
  workflow_dispatch:
  release:
    types: [published, deleted]


  # push:
  #   branch:
  #     - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://osskb.org
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      ## Get latest binaries URL
      - name: Set latest binary Download URL
        run:  
          echo "DOWNLOAD_URL=$(curl -s $TAG | grep browser_download_url | cut -d '"' -f 4)">> $GITHUB_ENV
        id: latest-binary
        env:
          TAG:  ${{ steps.latest.outputs.assets_url }}
      
      - name: Debug
        run: echo "${{ env.DOWNLOAD_URL }}"
      
      - name: Version info
        run: 'echo "Release to be deployed: ${{ steps.latest.outputs.tag_name }}"'
      
      ## Run Deployment Script deploy.sh (Download & Sync & Validate)

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.P12_SSH_PRIVATE_KEY }}
          name: id_ed25519 # optional
          known_hosts: ${{ secrets.P12_SSH_KNOWN_HOSTS }}
          config: ${{ secrets.P12_SSH_CONFIG }} # ssh_config; optional
          if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)

      - name: Deploy
        run: "./deploy.sh ${{ env.DOWNLOAD_URL }} ${{ steps.latest.outputs.tag_name }}"