---
name: "tagged-release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          # Artifact name
          # Destination path
          path: dist

      # - name: Uncompress file
      #   run: tar -xzvf dist/scanoss*/* -C dist

      - name: test output
        run: echo $(ls dist)

      - name: Set release folder
        run: echo "::set-output name=RELEASE_FOLDER::$(ls dist)
        id: set-release-folder

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            "dist/${{ steps.set-release-folder.outputs.RELEASE_FOLDER }}"/*
